unique_ids:
  assets:
    Nova Mentis Logo Green Round.png: '1751626006149902204152466.4419'
    standard-page.html: WXCZGTS6234TEPICXRLDVNREQ3G4CHVX
    theme.css: VQCAUXXHT7I2UEU3AO25IFCLFLORZDH5
  forms:
    HomePage: W6FZS2YACJXNHV3CKICLWCFH7XWPNHLK
    LoginPage: '1751626274810473800650186.7581'
  modules: {}
  scripts: {}
  server_modules: {}
